#!/usr/bin/env bash
#
# fix-hp-grub-boot.sh (Generated by Cluade)
#
# Automates the workaround for HP firmware that ignores the
# UEFI boot order  entries and always boots \EFI\Microsoft\Boot\bootmgfw.efi
#
# It works by:
#   1. Backing up the real Windows Boot Manager to EFI/Microsoft.bak
#   2. Putting GRUB's efi binary at the path the firmware hardcodes
#      (EFI/Microsoft/Boot/bootmgfw.efi)
#   3. Adding a GRUB menu entry that chainloads the real Windows Boot
#      Manager from the backup location
#   4. Enabling os-prober and regenerating grub.cfg
#
# Usage:
#   sudo ./fix-hp-grub-boot.sh          # apply the fix
#   sudo ./fix-hp-grub-boot.sh revert   # undo it (restore original Microsoft dir)

set -euo pipefail

ESP=/boot/efi
EFI_DIR="$ESP/EFI"
MS_DIR="$EFI_DIR/Microsoft"
MS_BAK="$EFI_DIR/Microsoft.bak"
CUSTOM_CFG=/etc/grub.d/40_custom
GRUB_DEFAULT=/etc/default/grub
MARKER="# --- HP Windows chainload fix (fix-hp-grub-boot.sh) ---"

if [[ $EUID -ne 0 ]]; then
  echo "Run this with sudo: sudo $0 $*" >&2
  exit 1
fi

# --- revert mode -----------------------------------------------------------
if [[ "${1:-}" == "revert" ]]; then
  if [[ ! -d "$MS_BAK" ]]; then
    echo "No backup found at $MS_BAK; nothing to revert." >&2
    exit 1
  fi
  rm -rf "$MS_DIR"
  mv "$MS_BAK" "$MS_DIR"
  echo "Reverted: $MS_DIR restored from backup, GRUB entry left in place (harmless if unused)."
  exit 0
fi

# --- sanity checks -----------------------------------------------------------
if [[ ! -d "$EFI_DIR" ]]; then
  echo "EFI directory $EFI_DIR not found -- is your ESP mounted at $ESP?" >&2
  exit 1
fi

if [[ -d "$MS_BAK" ]]; then
  echo "$MS_BAK already exists -- this looks like it's already been run." >&2
  echo "Run '$0 revert' first if you want to start over." >&2
  exit 1
fi

if [[ ! -d "$MS_DIR" ]]; then
  echo "No $MS_DIR found -- is Windows installed in UEFI mode?" >&2
  exit 1
fi

# locate grubx64.efi under EFI/<distro>/
GRUB_SRC=""
for d in "$EFI_DIR"/*/; do
  if [[ -f "${d}grubx64.efi" ]]; then
    GRUB_SRC="${d}grubx64.efi"
    break
  fi
done

if [[ -z "$GRUB_SRC" ]]; then
  echo "Could not find grubx64.efi under $EFI_DIR/*/." >&2
  echo "Contents of $EFI_DIR:" >&2
  ls "$EFI_DIR" >&2
  exit 1
fi
echo "Found GRUB EFI binary: $GRUB_SRC"

# --- 1. back up real Windows Boot Manager, install GRUB in its place -------
echo "Backing up $MS_DIR -> $MS_BAK"
mv "$MS_DIR" "$MS_BAK"

echo "Installing GRUB at $MS_DIR/Boot/bootmgfw.efi"
mkdir -p "$MS_DIR/Boot"
cp "$GRUB_SRC" "$MS_DIR/Boot/bootmgfw.efi"

# --- 2. find ESP UUID --------------------------------------------------------
ESP_DEV=$(findmnt -no SOURCE "$ESP")
ESP_UUID=$(blkid -s UUID -o value "$ESP_DEV")
echo "ESP device: $ESP_DEV   UUID: $ESP_UUID"

# --- 3. add chainload entry for Windows -------------------------------------
if grep -qF "$MARKER" "$CUSTOM_CFG" 2>/dev/null; then
  echo "Chainload entry already present in $CUSTOM_CFG, skipping."
else
  echo "Adding Windows chainload entry to $CUSTOM_CFG"
  cat >> "$CUSTOM_CFG" <<EOF

$MARKER
menuentry "Windows Boot Manager (manual)" {
    insmod part_gpt
    insmod fat
    search --no-floppy --fs-uuid --set=root $ESP_UUID
    chainloader /EFI/Microsoft.bak/Boot/bootmgfw.efi
}
EOF
fi

# --- 4. enable os-prober -----------------------------------------------------
if grep -q '^GRUB_DISABLE_OS_PROBER=' "$GRUB_DEFAULT"; then
  sed -i 's/^GRUB_DISABLE_OS_PROBER=.*/GRUB_DISABLE_OS_PROBER="false"/' "$GRUB_DEFAULT"
else
  echo 'GRUB_DISABLE_OS_PROBER="false"' >> "$GRUB_DEFAULT"
fi

if ! command -v os-prober >/dev/null 2>&1; then
  echo "Warning: os-prober is not installed (e.g. 'apt install os-prober')." >&2
fi

# --- 5. regenerate grub.cfg --------------------------------------------------
echo "Running os-prober..."
os-prober || true

echo "Regenerating grub.cfg..."
grub-mkconfig -o /boot/grub/grub.cfg

cat <<MSG

Done.
- GRUB now sits at the path HP's firmware always boots.
- The real Windows Boot Manager is preserved at $MS_BAK.
- Reboot and you should land in GRUB; the "Windows Boot Manager (manual)"
  entry will chainload into Windows.
- To undo everything later: sudo $0 revert
MSG
