# ~/.bashrc
#
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='\W \$ '
# if [[ -r /usr/share/bash-completion/bash_completion ]]; then
#   . /usr/share/bash-completion/bash_completion
# fi
#oh-my-bash
alias less='less -FSRXc'                    # Preferred 'less' implementation
alias wget='wget -c'                        # Preferred 'wget' implementation (resume download)
alias path='echo -e ${PATH//:/\\n}'         # path:         Echo all executable Paths
alias show_options='shopt'                  # Show_options: display bash options settings
bind 'set show-all-if-ambiguous on'
bind 'TAB:menu-complete'
bind '"\e[Z":menu-complete-backward'
# Switch git profiles; run in cloned repo dir
alias gitwork='git config user.name "USERNAME"; git config user.email "EMAIL"'
alias gitpersonal='git config user.name "USERNAME"; git config user.email "EMAIL"'
#Custom alias
alias 7zx='7z x'
alias rustcc='rustc -O -C prefer-dynamic'   # compact compiled size like C
alias fz='fd | sk -e --color=bw | xsel -b'
alias ac='aria2c -c --no-conf --console-log-level=warn --disable-ipv6=true --summary-interval=0 --download-result=hide -x 16 -j 16 -s 16 --allow-overwrite=true --allow-piece-length-change=true --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36" --check-certificate=false --show-console-readout=true --auto-file-renaming=false --file-allocation=none --uri-selector=inorder'
alias rpcd='aria2c -c --no-conf --enable-rpc --rpc-listen-all --console-log-level=warn --disable-ipv6=true --summary-interval=0 --file-allocation=none --retry-wait=5 --summary-interval=0 --disk-cache=64M --check-certificate=false --allow-piece-length-change=true --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36" -j 8 -x 8 -s 8'
alias cd..='cd ..'
alias chx='chmod +x'
alias chwn='sudo chown -R $USER'
alias cls='clear'
alias dc='f="$(fd | sk -e --color=bw)" && [ -z "$f" ] || cd "$f" || cd "$(dirname "$f")"'
alias nn='f="$(fd | sk -e --color=bw)" && [ -z "$f" ] || micro "$f" || nano "$f"'
alias e='subl'
alias vs='sudo micro'
# nnn: open file on enter | disable auto-enter on search | cli only opener | dont prompt for current if selected
alias lf='nnn -o -A -c -u'
alias filetype='xdg-mime query filetype'
alias fart='sd'
alias ls='eza'
alias la='eza -a'
alias ll='eza -la'
alias mpc='mpv --profile=720p'
alias audacious='audacious -e'
alias mpv='mpv --no-audio-display --volume=85'
alias play='m="$(fd -tf -e mp3 -e opus -e ogg -e m4a -e flac -e wav -e mkv -e webm -e mp4 -e m4v | sk -e --color=bw)"; [ -z "$m" ] || mpv --no-audio-display "$m"'
alias myip='curl icanhazip.com'
alias ipscan='sudo arp-scan --interface=enp2s0 --localnet'
alias off='sudo poweroff'
alias pack='7z a -m0=copy'
alias packx='7z a -m0=copy -p0000 -mhe'
alias rg='rg -i'
alias head='sed 11q'
alias rat='bat -p'
alias vi='micro'
alias view='viewnior'
alias o='viewnior'
alias cod='/usr/bin/code'
alias gc='git clone'
alias qr='qrencode -t ansiutf8 "$(xsel -b)"'
alias rn1='for i in *.*;do mv "$i" "$i"1;done' # append 1 to filename
alias rn1b='for i in *.*1;do mv "$i" "$(echo "$i"|choose -c 0..-1)";done' # remove 1 from filename
alias neofetch='fastfetch'
alias countdown='termdown -e --text "DONE"'
alias so='source ~/.bashrc'
alias wm='sudo micro /etc/X11/xinit/xinitrc || sudo nano /etc/X11/xinit/xinitrc'
alias pm='sudo micro /etc/pacman.d/mirrorlist || sudo nano /etc/pacman.d/mirrorlist'
# YT
alias yt='yt-dlp -4 --restrict-filenames --downloader aria2c'
alias ytx='yt-dlp -4 -x --restrict-filenames -o "%(title)s.%(ext)s"'
alias ytchapters='yt-dlp -4 --restrict-filenames --split-chapters'
alias ytf='yt-dlp -4 -F'
alias ytd='yt-dlp -4 --write-auto-subs --restrict-filenames --downloader aria2c'
alias ytt='yt-dlp -4 -f "bestvideo[height<=1080]+251" --restrict-filenames --downloader aria2c -o "%(title)s.%(ext)s"'
alias ytl='yt-dlp -4 --flat-playlist -i --print-to-file url yt_links.txt'
alias ytsub='yt-dlp -4 --write-auto-sub --skip-download'
# Conversion / Transcoding cutoff 18kHz for portability. Keep original file!
alias m4atomp3='for f in ./*.m4a; do echo "Converting.."; ffmpeg -i "$f" -acodec libmp3lame -joint_stereo 0 -q:a 2 -loglevel error "${f%.*}".mp3; done'
alias opustomp3='for f in ./*.opus; do echo "Converting.."; ffmpeg -i "$f" -acodec libmp3lame -joint_stereo 0 -q:a 2 -loglevel error "${f%.*}".mp3; done'
alias flactomp3='for f in ./*.flac; do echo "Converting.."; ffmpeg -i "$f" -acodec libmp3lame -joint_stereo 0 -q:a 2 -loglevel error "${f%.*}".mp3; done'
## yay mp3gain & https://github.com/dgilman/aacgain/releases/download/2.0.0/aacgain-2.0.0-linux-amd64
alias mp3gainer='for i in ./*.mp3; do mp3gain -r -k "$i";done'
alias aacgainer='for i in ./*.m4a; do aacgain -r -k "$i";done'
## https://github.com/FrancisRussell/zoog/releases/download/v0.8.1/zoog-v0.8.1-x86_64-unknown-linux-musl.tar.bz2
alias opusgainer='for i in ./*.opus; do opusgain -p rg -o track "$i";done'
alias opusgain_undo='opusgain -p original'
alias mp3gain_undo='for i in ./*.mp3; do mp3gain -u "$i"; done'
alias aacgain_undo='for i in ./*.m4a; do aacgain -u "$i"; done'
# Installs
alias syy='sudo pacman -Syy'
alias syu='sudo pacman -Syu'
alias installed='sudo pacman -Qe'
alias un='sudo pacman -Rns'
alias clean='sudo pacman -Scc && sudo pacman -Sc && yay -Sc'
alias py='python'
alias pi='uv pip install'
alias pl='uv pip list'
alias pu='uv pip uninstall'
alias pip='uv pip' # create virutalenv => # uv venv test1
alias sopy="source $HOME/.venv/bin/activate"
alias rf='ruff format'
alias uw='sudo wg-quick up'
alias dw='sudo wg-quick down'
alias uwg='sudo wg-quick up wg'
alias dwg='sudo wg-quick down wg'
alias dwgg='sudo wg-quick down wgg'
alias uwgg='sudo wg-quick up wgg'
alias mtu='sudo ip link set dev enp2s0 mtu'
alias ipd='sudo ip link set enp2s0 down'
alias ipu='sudo ip link set enp2s0 up'
alias rankmirrors='sudo reflector --threads 4 --sort rate --download-timeout 5 --country IN --age 6 --protocol http --fastest 10 --ipv4 --save /etc/pacman.d/mirrorlist'
alias d6='sudo modprobe tcp_bbr;sudo sysctl net.core.default_qdisc=cake;sudo sysctl net.ipv4.tcp_congestion_control=bbr; sudo sysctl net.ipv6.conf.default.disable_ipv6=1;sudo sysctl net.ipv6.conf.all.disable_ipv6=1;sudo sysctl net.ipv4.tcp_fastopen=3;sudo sysctl net.ipv4.tcp_mtu_probing=1;sudo sysctl net.ipv4.tcp_timestamps=0'
## [default]
alias ipa='sudo ~/scripts/setIP.sh enp2s0 192.168.0.111 192.168.0.1;echo default IP'
## [brigde mode]
# alias ipa='sudo ~/scripts/setIP.sh enp2s0 192.168.1.21 192.168.1.1;echo "bridge mode"'
## [pppoe connect]
# alias ipa='sudo ~/scripts/setIP.sh enp2s0 192.168.1.35 192.168.1.1;echo pppoe mode'

alias rr='xset r rate 240 40'
alias killdwm='killall dwm && exit'
alias ka='killall at-spi-bus-launcher;killall gvfsd;killall chrome_crashpad_handler;killall gvfsd-metadata;killall pipewire'
# Mount
alias mountt='sudo mount /dev/sda6 ~/T -o noatime,umask=000' ## NTFS drive
alias umountt='sudo umount ~/T && echo "[Removed]: T"'
alias umountsd='sudo umount ~/sd && echo "[Removed]: sd"'
alias dnsre="sudo systemctl restart --now dnscrypt-proxy.service"
alias psdrestart='systemctl --user restart psd.service'
alias psdenable='systemctl --user enable psd.service'
alias psddisable='systemctl --user disable psd.service'
alias psdstop='systemctl --user stop psd.service'
alias psdstart='systemctl --user start psd.service'
# SECRET EXTRAS
alias ms="miniserve -u -W -r -D -F -l --hide-theme-selector ."
alias gd="rclone mount VivoGdrive: $HOME/vivoGdrive/ --attr-timeout 1h --dir-cache-time 12h --vfs-read-chunk-size 32M --buffer-size 128M --vfs-cache-mode full"
alias rstemperature='xh -4 -pb -I --session=s --pretty=none --verify=no "https://www.accuweather.com/#" | htmlq -t ".header-temp"'

# export SSLKEYLOGFILE=~/.ssl-key.log
export XDG_SESSION_TYPE=x11
export VISUAL=subl
export EDITOR=micro
export LANG=en_US.UTF-8
export OPENSSL_CONF=/dev/null # for phantomjs
export LD_LIBRARY_PATH=/usr/local/lib
export SKIM_DEFAULT_COMMAND="fd --type f || git ls-tree -r --name-only HEAD || rg --files || find ."
export PATH=$HOME/.cargo/bin:$PATH
export PATH="$HOME/.local/bin:$PATH"
# Android 14 Dev
export ANDROID_HOME="$HOME/Android/Sdk"
export PATH=$ANDROID_HOME/cmdline-tools/bin:$PATH
# NNN configs
export NNN_PLUG="p:preview-tui"
export NNN_FIFO="/tmp/nnn.fifo"
export NNN_TERMINAL="st"
# intel VAAPI
export LIBVA_DRIVER_NAME=i965
export MESA_LOADER_DRIVER_OVERRIDE=i965
export MOZ_X11_EGL=1
export LIBGL_ALWAYS_SOFTWARE=0
# CTRL+R for command history
# CTRL+T to list files and dirs
eval "$(fzf --bash)"

# sudo cp -rf /opt/google/chrome/WidevineCdm /usr/lib/chromium/ # copy *.so file
# sudo ln -sf dash /bin/sh ## link dash to sh

## FOR MUSIC PLAYER :: gst-plugins-bad gst-plugins-good

## AUTO LOGIN
## sudo nano /etc/systemd/system/getty.target.wants/getty\@tty1.service
## find and replace with this: (username -> dra)
#<# ExecStart=-/sbin/agetty -o '-p -- \\u' --noclear - $TERM
#># ExecStart=-/sbin/agetty -a dra - $TERM

## update time:: sudo ntpdate -s time.nist.gov
## mp3 conv:: ffmpeg -i input.m4a -acodec libmp3lame -b:a 320k out.mp3
## add audio to video:: ffmpeg -i input.mp4 -i input.mp3 -c copy -map 0:v:0 -map 1:a:0 output.mp4
## trim video:: ffmpeg -i input.mp4 -ss 00:00:00 -t 00:03:16 -c:v copy -c:a copy short.mp4
