# Enable colors and change prompt:
autoload -U colors && colors
PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b "

# History in cache directory:
HISTSIZE=100
SAVEHIST=100
HISTFILE=~/.cache/zsh/history


# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)		# Include hidden files.

#Custom alias
alias 7zx='7z x'
alias rustcc="rustc -O -C prefer-dynamic"   # compact compiled size like C
alias fz='fd -H | fzf -i -e --algo=v1 | xsel -b'
alias ar='aria2c --http-auth-challenge=true --disable-ipv6=true --seed-time=0 --retry-wait=5 --summary-interval 5 --header="User-Agent: Mozilla/5.0" --file-allocation=falloc -c -j 4 -x 3 -s 3 -k 4M'
alias rpcd='aria2c --enable-rpc --rpc-listen-all --disable-ipv6=true --seed-time=0 --retry-wait=5 --summary-interval 5 --file-allocation=falloc -c -j 4 -x 3 -s 3 -k 5M'
alias cd..='cd ..'
alias chx='chmod +x'
alias cls='clear'
alias dc='f=$(fd | fzf --algo=v1 -i -e) && [ -z "$f" ] || cd "$f" || cd "$(dirname "$f")"'
alias nn='f=$(fd -H | fzf --algo=v1 -i -e) && [ -z "$f" ] || nano "$f"'
alias e='subl'
alias fart='sd'
alias ls='eza'
alias la='eza -a'
alias ll='eza -la'
alias zm='subl ~/.config/zsh/.zshrc'
alias mpc="mpv --profile=720p"
alias mpv='mpv --no-audio-display --replaygain=album'
alias play='m="$(fd -tf -e mp3 -e opus -e m4a -e flac -e wav -e mkv -e webm -e mp4 -e m4v -a | fzf --algo=v1 -i -e)" && [ -z $m ] || mpv --replaygain=album --no-audio-display "$m"'
alias myip='curl icanhazip.com'
alias off='sudo poweroff'
alias pack='7z a -m0=copy'
alias packx='7z a -m0=copy -p0000 -mhe'
alias rg='rg -i'
alias head='sed 11q'
alias fd='fd -H'
alias rat="bat -p"
alias vi='nvim'
alias neofetch='fastfetch'
alias countdown='termdown -e --text "DONE"'
alias zo='source ~/.zshrc'
alias wm='sudo nano /etc/X11/xinit/xinitrc'
# YT
alias yt="yt-dlp --restrict-filenames --cookies-from-browser chromium --downloader aria2c --external-downloader-args '-UMozilla/5.0 -c -j 4 -x 4 -s 4 -k 5M'"
alias yt="yt-dlp --restrict-filenames --downloader aria2c --external-downloader-args '-UMozilla/5.0 -c -j 4 -x 4 -s 4 -k 5M'"
alias ytx='yt-dlp -x --restrict-filenames'
alias ytf='yt-dlp -F'
alias ytd="yt-dlp --write-auto-subs --restrict-filenames --downloader aria2c --external-downloader-args '-UMozilla/5.0 -c -j 3 -x 3 -s 3 -k 5M'"
alias ytt="yt-dlp -f 'bestvideo[height<=1080]+251' --restrict-filenames --downloader aria2c"
alias ytl='yt-dlp --flat-playlist -i --print-to-file url yt_links.txt'
alias yts='yt-dlp -x --restrict-filenames --default-search "ytsearch" "$1"'
alias ytsub='yt-dlp --write-auto-sub --skip-download'

# Installs
alias syy='sudo pacman -Syy'
alias syu='sudo pacman -Syu'
alias install='sudo pacman -S'
alias installed='sudo pacman -Qe'
alias un='sudo pacman -Rns'
alias clean='sudo pacman -Scc && sudo pacman -Sc && yay -Sc'
alias py='python'
alias dwmmake='cd /home/dra/Desktop/Github/dwm/; sudo make install'
alias sopy='source bin/activate'
alias uw='sudo wg-quick up'
alias dw='sudo wg-quick down'
alias uwg='sudo wg-quick up wg'
alias dwg='sudo wg-quick down wg'
alias dwgg='sudo wg-quick down wgg'
alias uwgg='sudo wg-quick up wgg'
alias ipd='sudo ip link set enp2s0 down'
alias ipu='sudo ip link set enp2s0 up'
## default
alias ipa='sudo ~/Desktop/Github/setup/scripts/setIP.sh enp2s0 192.168.0.111 192.168.0.1;echo default mode'

## for brigde mode
# alias ipa='sudo ~/Desktop/Github/setup/scripts/setIP.sh enp2s0 192.168.1.11 192.168.1.1;echo "bridge mode"'

## for sudo pppd call sainet [pppoe connect]
# alias ipa='sudo ~/Desktop/Github/setup/scripts/setIP.sh enp2s0 192.168.1.35 192.168.1.1;echo pppoe mode'

alias mtu='sudo ip link set dev enp2s0 mtu'
alias killdwm='killall dwm'
alias ka='killall at-spi-bus-launcher;killall gvfsd;killall chrome_crashpad_handler;killall gvfsd-metadata;killall pipewire'
# Mount
alias mountt='sudo mount /dev/sda6 ~/T -o noatime,umask=000'
alias umountt='sudo umount ~/T'
alias umountsd='sudo umount ~/sd'
# SECRET EXTRAS
alias ms="miniserve -u -F -l --hide-theme-selector -D ."
alias gd="rclone mount VivoGdrive: /home/dra/vivoGdrive/"
alias rstemperature='xh -4 -p b -I --pretty=none "https://www.accuweather.com/en/in/shalimar-bagh/3588452/current-weather/3588452" | htmlq ".header-temp" --text'
alias replaygain='rsgain custom --tagmode=i --loudness=-12 --clip-mode=a --true-peak --opus-mode=d '

# export SSLKEYLOGFILE=~/.ssl-key.log
export XDG_SESSION_TYPE=x11
export VISUAL=subl
export EDITOR=subl
export LANG=en_US.UTF-8

# Load zsh-syntax-highlighting; should be last.
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null